### ISSUE TITLE
No output files after nominally successful run

### ISSUE THREAD

**Issue by sternj** [OSUSecLab/QtRE#2]
Running the tool with Java 11.0.22, maven 3.9.6, and GHidra 9.2.2 and the following configuration, the directory `result_dir` has no output. `corn_app_list` contains the absolute path of a binary called `corn_app`, which is a relatively large application using QT that I can provide privately upon request. 

```json
{
  "DIRECTORY_NAME": "/Users/sam/QtRE/ghidra_init_dir",
  "OUTPUT_DIR": "/Users/sam/QtRE/result_dir",
  "PROJECT_NAME": "corn_app",
  "BINARY_FILE_LIST": "./corn_app/corn_app_list",
  "LANGUAGE_NAME": "ARM:LE:32:v8",
  "DISASSEMBLE_TIMEOUT": 1000,
  "EMULATION_TIMEOUT": 30,
  "DECOMPILE_TIMEOUT": 60,
  "DECOMPILE_MODE": "decompile"
}
```

**Comment by sternj** [comment]
[Here is the console output](https://gist.github.com/sternj/1f4ac73ec43f3506b4cfccc26e228201), QtRE populates `result_dir` with two empty folders, `Connect` and `Meta`.

**Comment by onehouwong** [comment]
Hi, QtRE relies on the function signatures and symbols to recognize the connect functions and metadata tables. You results seem to suggest that QtRE was not able to locate them in the program to perform further analysis. Can you manually use Ghidra to confirm those functions / tables are found during runtime?
